<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;

class ExportTestUsers extends Command
{
    protected $signature = 'app:export-test-users
        {--path=docs/TEST_USERS.md : Output Markdown path (relative to base_path)}
        {--password=P@ssw0rd123 : The shared default password to check each hash against}';

    protected $description = 'Export a Markdown reference of every user (system + per-school) with their login password, for manual testing.';

    public function handle(): int
    {
        $default = (string) $this->option('password');

        $users = User::query()
            ->with(['roles', 'employee'])
            ->orderBy('school_id')
            ->orderBy('email')
            ->get();

        if ($users->isEmpty()) {
            $this->warn('No users found — nothing to export.');

            return self::SUCCESS;
        }

        // User has no school() relation — only a school_id column. Preload the
        // referenced schools (scopes off) into an id-keyed map.
        $schools = \App\Models\School::query()
            ->withoutGlobalScopes()
            ->whereIn('id', $users->pluck('school_id')->filter()->unique())
            ->get()
            ->keyBy('id');

        $pwLabel = fn (User $u): string => $u->password && Hash::check($default, $u->password)
            ? "`{$default}`"
            : '⚠ CUSTOM (not the shared default)';
        $roleLabel = fn (User $u): string => $u->roles->pluck('name')->implode(', ') ?: '—';

        [$system, $scoped] = $users->partition(fn (User $u) => $u->school_id === null);

        $lines = [];
        $lines[] = '# Test User Reference';
        $lines[] = '';
        $lines[] = '> **⚠ LOCAL DEV CREDENTIALS — DO NOT COMMIT OR SHARE.**';
        $lines[] = '> This file is git-ignored. All accounts use the shared password below '
            .'unless flagged otherwise. Generated by `php artisan app:export-test-users`.';
        $lines[] = '';
        $lines[] = 'Generated: '.now()->toDayDateTimeString();
        $lines[] = '';
        $lines[] = '- Total users: **'.$users->count().'**';
        $lines[] = '- Shared password: `'.$default.'`';
        $lines[] = '';

        $lines[] = '## System / cross-school accounts';
        $lines[] = '';
        $lines[] = '| Email | Role | Password |';
        $lines[] = '| --- | --- | --- |';
        foreach ($system->sortBy('email') as $u) {
            $lines[] = "| {$u->email} | {$roleLabel($u)} | {$pwLabel($u)} |";
        }
        $lines[] = '';

        $lines[] = '## Per-school accounts';
        $lines[] = '';

        $bySchool = $scoped->groupBy('school_id')
            ->sortBy(fn ($group) => optional($schools->get($group->first()->school_id))->name ?? '');

        foreach ($bySchool as $group) {
            $school = $schools->get($group->first()->school_id);
            $heading = $school
                ? "### [{$school->id}] {$school->name} ({$school->school_code})"
                : "### (school_id {$group->first()->school_id} — school record missing)";
            $lines[] = $heading;
            $lines[] = '';
            $lines[] = '| Email | Role | Name | Approval | Password |';
            $lines[] = '| --- | --- | --- | --- | --- |';
            foreach ($group->sortBy('email') as $u) {
                $name = optional($u->employee)->full_name ?: '—';
                $approval = $u->approval_status ?: '—';
                $lines[] = "| {$u->email} | {$roleLabel($u)} | {$name} | {$approval} | {$pwLabel($u)} |";
            }
            $lines[] = '';
        }

        // Footnotes: user-less schools and any non-default passwords.
        $schoolsWithUsers = $scoped->pluck('school_id')->unique();
        // Drop only SchoolScope (keep SoftDeletingScope) so trashed schools
        // are not mislabelled as "no user account".
        $userless = \App\Models\School::query()
            ->withoutGlobalScope(\App\Scopes\SchoolScope::class)
            ->whereNotIn('id', $schoolsWithUsers)
            ->orderBy('name')
            ->get(['id', 'name', 'school_code']);

        $custom = $users->filter(fn (User $u) => ! ($u->password && Hash::check($default, $u->password)));

        $lines[] = '## Notes';
        $lines[] = '';
        $lines[] = '- Schools with **no** user account: '
            .($userless->isEmpty()
                ? 'none'
                : $userless->map(fn ($s) => "[{$s->id}] {$s->name}")->implode('; '));
        $lines[] = '- Users **not** on the shared password: '
            .($custom->isEmpty() ? 'none' : $custom->pluck('email')->implode('; '));
        $lines[] = '';

        $path = $this->option('path');
        $abs = str_starts_with($path, '/') ? $path : base_path($path);
        @mkdir(dirname($abs), 0775, true);
        file_put_contents($abs, implode("\n", $lines)."\n");

        $this->info('Wrote '.$abs);
        $this->info("Users: {$users->count()} | system: {$system->count()} | school-scoped: {$scoped->count()} | schools: ".$bySchool->count());
        if ($custom->isNotEmpty()) {
            $this->warn($custom->count().' user(s) are NOT on the shared password (flagged in the file).');
        }

        return self::SUCCESS;
    }
}
